# Refactor-base runtime variables
PROFILE={{PROFILE}}
DOMAIN={{DOMAIN}}
UUID={{UUID}}
WS_PATH={{WS_PATH}}
NODE_NAME={{NODE_NAME}}
XRAY_PORT={{XRAY_PORT}}
TLS_MODE={{TLS_MODE}}
TLS_EMAIL={{TLS_EMAIL}}
TLS_CA={{TLS_CA}}
CADDY_HTTP_PORT={{CADDY_HTTP_PORT}}
CADDY_HTTPS_PORT={{CADDY_HTTPS_PORT}}
CADDY_ADMIN_PORT={{CADDY_ADMIN_PORT}}
XRAY_IMAGE={{XRAY_IMAGE}}
CADDY_IMAGE={{CADDY_IMAGE}}
XRAY_LOG_LEVEL={{XRAY_LOG_LEVEL}}
ENABLE_FAKE_SITE={{ENABLE_FAKE_SITE}}
