# Refactor-base runtime variables
PROFILE={{PROFILE}}
DOMAIN={{DOMAIN}}
UUID={{UUID}}
NODE_NAME={{NODE_NAME}}
XRAY_PORT={{XRAY_PORT}}
TLS_MODE={{TLS_MODE}}
XRAY_IMAGE={{XRAY_IMAGE}}
XRAY_LOG_LEVEL={{XRAY_LOG_LEVEL}}
REALITY_SERVER_NAME={{REALITY_SERVER_NAME}}
REALITY_DEST={{REALITY_DEST}}
REALITY_PUBLIC_KEY={{REALITY_PUBLIC_KEY}}
REALITY_SHORT_ID={{REALITY_SHORT_ID}}
REALITY_FINGERPRINT={{REALITY_FINGERPRINT}}
REALITY_SPIDER_X={{REALITY_SPIDER_X}}
REALITY_FLOW={{REALITY_FLOW}}
